spring:

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://26.175.81.229:5432/chat
    username: postgres
    password: root

secret: secretksecretisecretm
server:
  port: 8080
